traPtitech/trap-collection-server

- docs/schema.md
- mysql/init/1_create_db.sql
> Schema.md作成

- docs/schema.md
- docs/swagger.yaml
DB SchemaとSwaggerを修正しました。チェックお願いします。
Close #10
> Schema,swagger修正

- docs/schema.md
- docs/swagger.yaml
> 管理者周りのエンドポイントの追加

- .github/workflows/main.yaml
GoのlintのチェックをGithub Actionsに追加しました。
> Goのlintの追加

- docs/openapi.yml
> エンドポイントのキャメルケースへの変更

- docs/swagger/index.html
> 今度こそ見られるようにした

- docs/swagger/openapi.yml
PUT /games/{gameID}/info・POST /games のrequestBodyの修正。
DELETE /games/{gameID}/info をDELETE /games/{gameID} へ変更。
> `/games/{gameID}/info`関連エンドポイントの修正

- docs/swagger/openapi.yml
> /games/asset/{gameID}/url修正した

- docs/swagger/openapi.yml
> swaggerへ/games?all=trueの追加

- docs/swagger/openapi.yml
> versionのリクエストボディ修正

- README.md
- docker/dev/docker-compose.yml
- generate/controller-api.mustache
- generate/interfaces.mustache
- model/db.go
- model/game_versions.go
- model/launcher_versions.go
- model/players.go
- model/product_keys.go
- router/base/auth_impl.go
- router/game.go
- router/game_test.go
- router/middleware.go
- router/seat.go
- router/version.go
> 既実装部分のバグ取り

- generate/controller-api.mustache
- go.mod
- go.sum
- model/games.go
- model/maintainers.go
- router/game.go
- router/game_test.go
- router/service.go
> POST /games実装

- router/base/auth.go
- router/base/auth_impl.go
- router/service.go
- router/user.go
> GET /users実装

- model/games.go
- router/game.go
実装した。
変更したファイルでgofmtした結果関係ない変更が一部出ているけど許して…
> PUT /games/:gameID/info実装

- generate/controller-api.mustache
- generate/generator.groovy
- router/game.go
generatorの修正をした。
変更点
- エラーハンドリングをechoのドキュメントにのってecho.NewHTTPErrorでするように
- echo.Contextが3つ引数があるうちの2つ目とかの中途半端な番目の引数になることがあり気持ち悪かった問題の修正
> generator修正

- model/games.go
GET /gamesでバージョンが作られていないゲームが消えていたので修正した。
> GET /games修正

- model/game_versions.go
- router/game.go
> GET /games/:gameID/version実装

- model/games.go
`GET /games/:gameID/info`がヌルポになって500が発生していたので直した。
> GET /games/:gameID/infoが500になっていた

- model/launcher_versions.go
- router/middleware.go
- router/version.go
実装した。途中でランチャー関連の修正権限の処理をするmiddlewareのミスで誰もランチャー関連の修正ができなくなっていることに気がついたのでその修正もした。
> POST /versions実装

- model/db.go
- model/db_mock.go
- model/game_assets.go
- model/maps.go
- router/game.go
> POST /games/asset/:gameID/url実装

- docs/swagger/openapi.yml
- model/launcher_versions.go
- router/version.go
実装した。
ゲーム一覧を入れないようにするopenapiの変更も入れた。
> GET /versions実装

- README.md
- docker/dev/Dockerfile
- docker/mock/mock.Dockerfile
- docker/mock/server.Dockerfile
- docker/staging/Dockerfile
docker imageのupdate。m1 macで動かすときにarm用imageがないものだと辛いのでできるだジェ早めに確認頼む:pray:
> docker image update

- docs/swagger/openapi.yml
widthとheightをrequestBodyに入れていなかったので修正
> 席バージョン作成のAPI修正

- docs/swagger/openapi.yml
- model/games.go
> GET /games/{gameID}/infoにdescription追加

- docs/swagger/openapi.yml
ここだけアッパーキャメルケースなのは不自然なので修正。
Close #95
> SeatingTimeをseatingTimeに

- docs/schema.md
- docs/swagger/openapi.yml
- go.mod
- go.sum
- model/db.go
- model/game_assets.go
- model/game_versions.go
- router/game.go
> POST /games/asset/{gameID}/file実装

- docs/schema.md
- docs/swagger/openapi.yml
- model/db.go
- model/game_assets.go
- model/game_versions.go
- model/games.go
- router/game_test.go
> game version idをUUIDに

- docs/schema.md
- model/games.go
- model/maintainers.go
uuidにした。
apiへの影響はないのでopenapiは変更していない。
> maintainer idをUUIDに

- docs/schema.md
- model/db.go
- model/game_introductions.go
UUIDにした。
これはエンドポイントには使われないのでopenapiに変更はない。
> game introductionのIDをUUIDに

- docs/schema.md
- model/launcher_versions.go
名前を変えた。
ref: https://github.com/traPtitech/trap-collection-server/pull/71#discussion_r631500261
Close #110
> dbのanke_toカラムをanke_to_urlに

- docs/schema.md
- model/access_tokens.go
UUIDにした。
まだ実装していない、かつ、APIに出てこない値なのでschemeとgorm用の構造体の修正のみ。
> access tokenのIDをUUIDに

- docs/schema.md
- model/game_assets.go
- model/maps.go
- model/product_keys.go
UUIDにした。
ミスでAPIはuuidになっているのにDBはauto incrementになっていたっぽいので、OpenAPIに修正はなし。
> product keyをuuidに

- docs/schema.md
- docs/swagger/openapi.yml
- model/seat_versions.go
- model/seats.go
uuidにした。
uuidへの変更関連のPRまとめた方が良いという話だったのでまとめた。
> seat idとseat version idをUUIDに

- docs/schema.md
- docs/swagger/openapi.yml
- model/db.go
- model/game_version_relations.go
- model/launcher_versions.go
- model/product_keys.go
- router/base/auth.go
- router/base/auth_impl.go
- router/base/auth_test.go
- router/version.go
versionIDは推測されると明らかにまずいのでUUIDにする。
> versionIDをUUIDに

- .github/dependabot.yaml
- .github/workflows/main.yaml
- .github/workflows/master.yaml
- docker/dev/Dockerfile
- docker/mock/mock.Dockerfile
- docker/mock/server.Dockerfile
- docker/staging/Dockerfile
- dependabot対応
- ブランチ運用変更対応
- goのバージョン更新
- ghcr対応
- マルチステージビルド対応
> GitHub Actionsなどいろいろの更新

- pkg/context/keys.go
> context管理用package

- go.mod
- pkg/random/string.go
- src/domain/launcher_session.go
- src/domain/launcher_session_test.go
- src/domain/launcher_user.go
- src/domain/launcher_version.go
- src/domain/values/launcher.go
- src/domain/values/launcher_test.go
> ランチャー周りのドメイン作成

- src/domain/launcher_user.go
- src/domain/values/launcher.go
- `NewLauncherUser`でインスタンスを返していたのを、ポインタを返すように修正
- uuid系の値オブジェクトのコンストラクタ修正
> ランチャー周りのドメインの修正

- src/repository/errors.go
- src/repository/launcher_session.go
- src/repository/launcher_user.go
- src/repository/launcher_version.go
- src/service/errors.go
- src/service/launcher_auth.go
- src/service/v1/launcher_auth.go
- src/service/v1/launcher_auth_test.go
> LauncherAuthサービス作成

- generate/controller-api.mustache
- src/handler/v1/api.go
- src/handler/v1/launcher_auth.go
- src/handler/v1/launcher_auth_test.go
- src/service/launcher_auth.go
handler実装した。
あとwireでの繋ぎこみをすれば認証周りのAPIを稼働できる。
> launcher認証周りのhandler実装

- model/db.go
> migrateの修正

- pkg/common/types.go
- src/auth/oidc.go
- src/domain/values/oidc.go
- src/service/errors.go
- src/service/oidc.go
- src/service/v1/oidc.go
- src/service/v1/oidc_test.go
> traPメンバーかの認証用サービス作成

- .github/workflows/main.yaml
testを行うGitHub Actionsを追加した。
新しいアーキテクチャでの実装がある`src`全体のテストをするようにしている。
> test用action追加

- src/repository/errors.go
- src/repository/gorm2/game_management_role.go
- src/repository/gorm2/game_management_role_test.go
- src/repository/gorm2/tables.go
- src/repository/lock_types.go
> ゲーム管理周りのrepository実装

- src/repository/gorm2/db.go
- src/repository/gorm2/game.go
- src/repository/gorm2/game_management_role.go
- src/repository/gorm2/game_test.go
ゲームの管理者の認証周りの実装に必要なゲームテーブルの操作を実装した。
また、ロックの設定を他の場所でも使いそうだったので切り出した。
> ゲーム周りのrepositoryの一部実装

- pkg/common/types.go
- src/service/administrator_auth.go
- src/service/v1/administrator_auth.go
- src/service/v1/administrator_auth_test.go
作った。
一応旧実装とは微妙に変えて環境変数から管理者を読むこむようにしようかと思っている。
いずれもっとまともな形で実装し直す必要があるのは同様。
> アプリケーションの管理者管理まわりのサービス作成

- pkg/common/types.go
- src/storage/errors.go
- src/storage/local/directory_manager.go
- src/storage/local/directory_manager_test.go
- src/storage/local/game_image.go
- src/storage/local/game_image_test.go
> GameImageのローカルストレージ実装

- src/repository/game_image.go
- src/repository/gorm2/game_image.go
- src/repository/gorm2/game_image_test.go
- src/repository/gorm2/tables.go
- src/service/v1/game_image.go
- src/service/v1/game_image_test.go
実装した。
GetGameImageよりGetLatestGameImageの方が実態を表していてより適切だったので名前を変更している。
> GameImageリポジトリ実装

- src/repository/gorm2/game_management_role.go
テストの際に並列で実行されるが、FirstOrCreateはロックを取らないため同時実行されるとエラーになりテストに落ちる可能性があった。
singleflightを用いてNewGameManagementRoleを並列実行可能にした。
> NewGameManagementRoleの並列実行対応

- router/game.go
- router/service.go
- src/handler/v1/api.go
- src/handler/v1/game_image.go
- src/handler/v1/game_image_test.go
- src/handler/v1/util_test.go
- src/wire.go
- src/wire_gen.go
> GameImageハンドラー実装

- .gitignore
- docker/dev/docker-compose.yml
- main.go
オブジェクトストレージ周りの環境変数を読み込み忘れており、stagingがRestartingになっていたので修正した。
> オブジェクトストレージの環境変数を読み込み忘れていた

- main.go
- pkg/common/types.go
- src/storage/swift/client.go
- src/storage/swift/client_test.go
- src/wire.go
- src/wire_gen.go
TennantNameがなく認証に失敗していたので修正した。
> TennantName追加

- src/storage/local/game_video.go
- src/storage/local/game_video_test.go
> GameVideoのlocalストレージへの保存実装

- src/storage/swift/game_video.go
- src/storage/swift/game_video_test.go
> GameVideoのswiftストレージ実装

- src/repository/gorm2/game_video.go
- src/repository/gorm2/game_video_test.go
- src/repository/gorm2/tables.go
> GameVideoリポジトリ実装

- docker/dev/Dockerfile
- docker/mock/server.Dockerfile
- docker/test/Dockerfile
> dockerizeのtimeout設定

- router/game.go
- router/service.go
- src/handler/v1/api.go
- src/handler/v1/game_video.go
- src/handler/v1/game_video_test.go
- src/service/errors.go
- src/service/v1/game_video.go
- src/service/v1/game_video_test.go
- src/wire.go
- src/wire_gen.go
> GameVideoのハンドラー実装

- src/repository/game_version.go
- src/service/game_version.go
- src/service/v1/game_version.go
- src/service/v1/game_version_test.go
> GemeVersionサービス実装

- src/repository/gorm2/game_version.go
- src/repository/gorm2/game_version_test.go
- src/repository/gorm2/tables.go
> GameVersionのリポジトリ実装

- router/game.go
- router/service.go
- src/handler/v1/api.go
- src/handler/v1/game_version.go
- src/handler/v1/game_version_test.go
- src/handler/v1/launcher_auth_test.go
- src/repository/gorm2/game_version_test.go
- src/service/game_version.go
- src/service/v1/game_version_test.go
- src/service/v1/launcher_auth_test.go
- src/wire.go
- src/wire_gen.go
> GameVersionのハンドラー実装

- src/domain/game_file.go
- src/domain/values/launcher_environment.go
- src/domain/values/launcher_environment_test.go
- src/repository/game_file.go
- src/repository/game_version.go
- src/service/errors.go
- src/service/game_file.go
- src/service/v1/game_file.go
- src/service/v1/game_file_test.go
- src/storage/game_file.go
- src/storage/mock/game_file.go
実装した。
Launcherの動作環境を表すLauncherEnvirontドメインが不足していたので追加している。
また、GameVersionリポジトリのメソッドにGetLatestGameVersionを追加したことで`gorm2.GameVersion`がインターフェイスを満たさなくなり、コンパイルが現段階では通らなくなっているので`feature/game_service`ブランチへのPRにしている。
> GemFileサービス実装

- src/repository/gorm2/game_version.go
- src/repository/gorm2/game_version_test.go
> GemeVersionリポジトリにGetLatestGameVersion追加実装

- src/service/errors.go
- src/service/v1/game_file.go
- src/service/v1/game_file_test.go
SaveGameFileを既に同じ種類のファイルが存在する場合エラーになるようにした。
> SaveGameFileで既にファイルがある時エラー

- src/domain/values/game_file.go
- src/repository/gorm2/game_file.go
- src/repository/gorm2/game_file_test.go
- src/repository/gorm2/tables.go
実装した。
また、`NewGameFileIDFromUUID`に誤りがあったので、その修正もしている。
> GameFileリポジトリ実装

- src/storage/local/game_file.go
- src/storage/local/game_file_test.go
> GameFileストレージ実装(ローカル)

- src/storage/swift/game_file.go
- src/storage/swift/game_file_test.go
本番用のswiftストレージを使用するGameFileストレージを実装した。
> GameFileストレージ実装(swift)

- src/repository/game_url.go
- src/service/errors.go
- src/service/game_url.go
- src/service/v1/game_url.go
- src/service/v1/game_url_test.go
> GameURLサービス実装

- src/repository/gorm2/game_url.go
- src/repository/gorm2/game_url_test.go
- src/repository/gorm2/tables.go
> GameURLリポジトリ実装

- router/game.go
- router/service.go
- src/handler/v1/api.go
- src/handler/v1/game_url.go
- src/handler/v1/game_url_test.go
- src/service/game_url.go
- src/wire.go
- src/wire_gen.go
> GameURLハンドラー実装

- src/domain/game_video.go
- src/repository/gorm2/game_video.go
- src/repository/gorm2/game_video_test.go
- src/service/v1/game_video.go
- src/service/v1/game_video_test.go
- src/storage/local/game_video_test.go
- src/storage/swift/game_video_test.go
GameImageと同様の理由でcreatedAtが必要だったので追加した。
> GameVideoドメインにcreatedAt追加

- src/domain/game_file.go
- src/handler/v1/game_file_test.go
- src/repository/gorm2/game_file.go
- src/repository/gorm2/game_file_test.go
- src/repository/gorm2/tables.go
- src/service/v1/game_file.go
- src/service/v1/game_file_test.go
- src/storage/local/game_file_test.go
- src/storage/swift/game_file_test.go
GameImageなどと同様に、/versions/checkで必要なので追加した。
> GameFileドメインにCreatedAt追加

- go.mod
- go.sum
- src/domain/game_url.go
- src/handler/v1/game_url_test.go
- src/repository/gorm2/game_url.go
- src/repository/gorm2/game_url_test.go
- src/repository/gorm2/tables.go
- src/service/v1/game_url.go
- src/service/v1/game_url_test.go
GameImageとかと同じ理由でcreatedAt追加した。
> GameURLドメインにcreatedAt追加

- src/repository/gorm2/launcher_version.go
- src/repository/gorm2/launcher_version_test.go
- src/repository/gorm2/tables.go
- src/service/v1/launcher_auth.go
> ランチャーバージョンリポジトリへのメソッド追加

- src/repository/gorm2/game.go
- src/repository/gorm2/game_test.go
Gameリポジトリにメソッドを追加した。
GetGameInfosByLauncherVersionが大変なことになっているが、今治していると間に合わないので一旦放置する。
> Gameリポジトリにメソッド追加

- docs/swagger/openapi.yml
- src/handler/v1/launcher_auth.go
- src/handler/v1/launcher_auth_test.go
> GET /launcher/me実装

- src/handler/v1/launcher_version.go
- src/handler/v1/launcher_version_test.go
ハンドラーで動画が存在しない場合無視する実装をしてしまっていたため、空配列となっていた。
> GetCheckListのnilの処理修正

- main.go
- src/repository/db.go
- src/repository/gorm2/db.go
- src/repository/mock/db.go
- src/wire.go
- src/wire_gen.go
mainで新実装の方のDBのCloseをしていなかったのでするようにした。
これでconnection leakが治ってくれればいいけど、connectionの増え方見た感じならなさそう。
> DBのClose対応

- .github/dependabot.yaml
設定が誤っており、正常にdependabotが動いていなかった。
> github actionsの更新修正

- src/repository/game.go
- src/repository/game_version.go
- src/service/game.go
- src/service/launcher_version.go
- src/service/v1/game.go
- src/service/v1/game_test.go
実装した。
repositoryにいくつかメソッドを追加した関係でbuildできなくなっているのでmainにはまだマージしない。
> Gameサービス実装

- src/repository/gorm2/game.go
- src/repository/gorm2/game_test.go
- src/repository/gorm2/game_version.go
- src/repository/gorm2/game_version_test.go
Gameサービスで必要になったrepositoryのメソッドを実装した。
> Gameサービス関連のrepository修正

- src/repository/game.go
- src/repository/game_version.go
- src/repository/gorm2/game.go
- src/repository/gorm2/game_test.go
- src/repository/gorm2/game_version.go
- src/repository/gorm2/game_version_test.go
- src/service/game.go
- src/service/launcher_version.go
- src/service/v1/game.go
- src/service/v1/game_test.go
実装した。
handlerがまだ実装できていないため、置き換わってはいない。
> ゲーム関連のservice,repository実装

- src/handler/v1/game.go
> GET /gamesのallのデフォルト値設定

- go.mod
> Goのパッケージのアップデート(go.mod)

- go.mod
- go.sum
- src/repository/gorm2/db.go
- src/repository/gorm2/game_image.go
- src/repository/gorm2/game_management_role.go
- src/repository/gorm2/game_video.go
- src/repository/gorm2/metrics.go
- src/repository/gorm2/tables.go
gormのprometheusプラグインを使ってDB周りのメトリクスを取るようにした。
> DB周りのメトリクス追加

- src/storage/swift/client.go
- src/storage/swift/client_test.go
- src/storage/swift/game_file.go
- src/storage/swift/game_file_test.go
- src/storage/swift/game_image.go
- src/storage/swift/game_image_test.go
- src/storage/swift/game_video.go
- src/storage/swift/game_video_test.go
cacheのhit rateをメトリクスとして吐くようにした。
> storageのswift実装にcacheのhit rateのメトリクス追加

- src/storage/swift/game_file.go
- src/storage/swift/game_image.go
- src/storage/swift/game_video.go
promautoを使っておらず、registerされていなかったのでpromautoを使うようにした。
> storageのメトリクスにpromauto使用

- src/storage/swift/cache.go
- src/storage/swift/client.go
- src/storage/swift/client_test.go
- src/wire.go
- src/wire_gen.go
https://github.com/djherbis/fscache
を使っていたが、ディスクの使用量にlimitがかけられないようでこのままだとdiskが溶けてしまうことがわかった。
この対応でキャッシュを
パフォーマンスは落ちるが自前実装の5GBまでキャッシュするLRUに切り替えた。
> storageのcacheを自前実装に切り替え

- main.go
- src/storage/swift/client.go
- src/storage/swift/client_test.go
- src/storage/swift/game_file.go
- src/storage/swift/game_file_test.go
- src/storage/swift/game_image.go
- src/storage/swift/game_image_test.go
- src/storage/swift/game_video.go
- src/storage/swift/game_video_test.go
- src/wire.go
- src/wire_gen.go
今の実装だとdiskがとける。
また、今から実装入れ替えるのは間に合わないので、キャッシュ機能を消す。
ここまで挙動を見る限り、キャッシュがなくてもサーバーは持つと思われる。
> ファイルキャッシュ機能削除

- src/repository/gorm2/metrics.go
- src/storage/swift/client_test.go
- src/storage/swift/game_file_test.go
- src/storage/swift/game_image_test.go
- src/storage/swift/game_video_test.go
access tokenのメトリクスが誤っていたので修正した。
> access tokenのメトリクス修正

- docs/swagger/openapi.yml
> version require null

- src/handler/v1/game.go
- src/service/game.go
- src/service/v1/game.go
- src/service/v1/game_test.go
- src/wire_gen.go
管理者権限をゲーム追加時に追加していなかったので、追加するよう修正した。
> Game追加時に管理者権限を追加するように

- src/handler/v1/middleware.go
- src/handler/v1/middleware_test.go
> 管理者にゲーム更新権限追加

- src/service/v1/game_file.go
並列で数十個とか走るともたないので、制限するようにした。
とりあえず確実に耐えられるラインとして2並列までに制限している。
> Gameファイルの並列ダウンロード数制限

- src/handler/v1/game_test.go
- src/service/game.go
> Gameハンドラーのテスト追加

- generate/model.mustache
- src/handler/v1/launcher_version.go
- src/handler/v1/launcher_version_test.go
movieUpdatedAtをtime.Timeのポインタにしてnullableにした。
> movieUpdatedAtを存在しない時空に

- docs/swagger/openapi.yml
- src/domain/values/game_video.go
- src/handler/v1/game_video.go
- src/handler/v1/game_video_test.go
- src/service/game_video.go
- src/service/v1/game_video.go
- src/service/v1/game_video_test.go
- src/storage/game_video.go
- src/storage/local/game_video.go
- src/storage/mock/game_video.go
- src/storage/swift/game_video.go
GameVideoもGameFileと同様にTmpURLへredirectするよう変更した。
> GameVideoのredirect

- .github/workflows/release.yaml
> releaseのaction修正

- README.md
> README修正漏れ

- docs/images/application.drawio.svg
- docs/images/overview.drawio.svg
- src/README.md
> 設計についての説明追加

- src/README.md
> srcのREADME修正

- docs/swagger/openapi.yml
- src/domain/values/game_image.go
- src/handler/v1/game_image.go
- src/handler/v1/game_image_test.go
- src/handler/v1/openapi/api_game.go
- src/service/game_image.go
- src/service/v1/game_image.go
- src/service/v1/game_image_test.go
- src/storage/game_image.go
- src/storage/local/game_image.go
- src/storage/mock/game_image.go
- src/storage/swift/game_image.go
GameImageもGameFileやGameVideoと同様にTmpURLへredirectするよう変更しました。
> GameImageのリダイレクト

- docker/production/Dockerfile
#399 でbuild stageのキャッシュを消し忘れていた。
> productionのDockerfileからのキャッシュの除去

- src/storage/swift/game_image_test.go
画像生成しているテストがまだ生きていたので、testdataを使うようにした。
> swift packageの画像テスト高速化

- docs/openapi/v2.yaml
`deleteGames`を他に揃えて`deleteGame`に変更。
PATCHメソッドなのに`putGame`となっていたので、`patchGame`に変更。
> operation名修正

- src/cache/ristretto/user.go
userキャッシュの実装に`GetActiveUsers`、`SetActiveUsers`を追加した。
まだauthに不足しているメソッドが存在し、buildが通らないので、一旦mainとは別のブランチにPRを出している。
> userキャッシュの実装修正

- src/cache/ristretto/user_test.go
追加したメソッドのテストを追加し忘れていたので追加した。
ref #421
> userキャッシュのテスト追加

- src/auth/traQ/user.go
- src/auth/traQ/user_test.go
traQでの認証の実装に`GetActiveUsers`を追加した。
> traQでの認証にGetActiveUsers追加

- src/handler/v2/oauth2.go
- src/handler/v2/oauth2_test.go
- src/handler/v2/session.go
- src/handler/v2/session_test.go
> OAuth2ハンドラー実装

- src/handler/v2/checker.go
> traPのメンバーかチェックするChecker実装

- src/handler/v2/oauth2_test.go
- src/wire/config.go
- src/wire/service.go
- src/wire/wire_gen.go
wireの設定を修正した。
serviceのinjectionがv2の設定に対応させていなかったので、それもしてしまっている。
> 認証まわりのwire設定

- docs/openapi/v2.yaml
OpenAPIでfile、image、videoの一覧取得のAPIでレスポンスがarrayになっていなかったので修正した。
> OpenAPIのファイル関連のGETをarrayに修正

- docker/test/compose.yaml
testでv2 APIをonにできておらず、v2のDB周りのテストができなかったのを修正した。
> testでv2 APIをonに

- src/repository/gorm2/v2_game_image.go
- src/repository/gorm2/v2_game_image_test.go
> ゲーム画像(v2)のrepository実装

- src/handler/v2/api.go
- src/handler/v2/game_image.go
- src/handler/v2/game_image_test.go
- src/repository/gorm2/v2_game_image.go
- src/repository/gorm2/v2_game_image_test.go
- src/repository/v2_game_image.go
- src/service/errors.go
- src/service/v2/game_image.go
- src/service/v2/game_image_test.go
- src/service/v2_game_image.go
- src/wire/repository.go
- src/wire/service.go
- src/wire/wire_gen.go
> ゲーム画像関連API実装

- src/handler/v2/game.go
- src/handler/v2/game_test.go
- src/service/v2_game.go
> game関連のAPIのhandler実装

- src/repository/v2_game.go
- src/repository/v2_game_video.go
- src/service/errors.go
- src/service/v2/game_video.go
- src/service/v2/game_video_test.go
- src/service/v2_game_video.go
(間違ってmainにマージしようとしてたのでもう一回）
した。ほとんど画像のやつを持ってきてimage->video,画像->動画の変換をしただけ。
ただ、imageのほうではrepositoryのGameはv1のものを使っていたが、GameV2の実装は終わっているので、videoではGameV2を使っている。
> game動画関連のservice実装

- src/repository/gorm2/v2_game_video.go
- src/repository/gorm2/v2_game_video_test.go
> game動画関連のAPIのrepository実装

- src/handler/v2/game_video.go
- src/handler/v2/game_video_test.go
- src/wire/repository.go
- src/wire/service.go
- src/wire/wire_gen.go
> game動画関連のAPIのhandler実装

- src/handler/v2/game_version.go
- src/handler/v2/game_version_test.go
実装した。
wireの設定がまだなので、buildは通らない。
> ゲームバージョンハンドラー実装

- src/repository/gorm2/v2_game_file.go
- src/repository/gorm2/v2_game_file_test.go
実装した。
wireの設定がまだなのでbuildは通らない。
> ゲームファイルリポジトリ(ゲームバージョンで使う部分のみ)実装

- src/repository/gorm2/edition.go
- src/repository/gorm2/v2_game.go
- src/repository/gorm2/v2_game_version.go
- src/service/edition.go
実装した。
ただし、ユニットテストが欠けていないため、正常に動作するかはまだ不明。
> エディション関係のリポジトリ実装

- src/repository/v2_game_file.go
- src/service/errors.go
- src/service/v2/game_file.go
- src/service/v2/game_file_test.go
- src/service/v2_game_file.go
> ゲームファイル関連のAPIサービス実装

- src/repository/gorm2/v2_game_file.go
- src/repository/v2_game_file.go
- src/service/v2/edition.go
- src/service/v2/game_file.go
- src/service/v2/game_file_test.go
- src/service/v2/game_version.go
- src/service/v2/game_version_test.go
- src/service/v2_game_file.go
した。mazreanさんが書いた`GetGameFiles`は`GetGameFilesWithoutTypes`になった。他のファイルでの対応を忘れていたので、その修正もここに含まれている。
テストはmazreanさんが書いた`GetGameFilesWithoutTypes`のみ。
> ゲームファイル関連のAPIのrepository実装

- src/repository/gorm2/access_token.go
- src/repository/gorm2/migrate/current.go
- src/repository/gorm2/migrate/migrate.go
- src/repository/gorm2/migrate/v6.go
- src/repository/gorm2/product_key.go
- src/repository/product_key.go
- src/service/v2/edition_auth.go
> エディションの認可周りのリポジトリ実装

- src/handler/v2/game_file.go
- src/repository/gorm2/v2_game_file.go
- src/repository/v2_game_file.go
- src/service/v2/game_file.go
- src/service/v2/game_file_test.go
- src/service/v2_game_file.go
- src/wire/service.go
- src/wire/wire_gen.go
した。テストは未追加。wire対応を含んでおり、ローカルでの動作を確認した。
> gameファイル関連のAPIのhandler実装

- src/handler/v2/game_file.go
- src/repository/gorm2/v2_game_file.go
- src/repository/gorm2/v2_game_file_test.go
- src/repository/v2_game_file.go
- src/service/v2/edition.go
- src/service/v2/game_file.go
- src/service/v2/game_file_test.go
- src/service/v2/game_version.go
- src/service/v2/game_version_test.go
- src/service/v2_game_file.go
- src/wire/service.go
- src/wire/wire_gen.go
した。ローカルでの動作確認済み。
テストは、serviceとrepositoryの`GetGameFilesWithoutType`のみ存在して、他は追加されていない。
> ゲームファイル関連のAPI実装

- src/service/v2/game_role.go
- src/service/v2_errors.go
- src/service/v2_game_role.go
した。テストは追加していない。
repositoryはv1のものをそのまま使っている。
> ゲーム権限関連のAPIのservice実装

- docs/openapi/v2.yaml
- src/handler/v2/game_role.go
- src/service/v2/game_role.go
- src/service/v2_errors.go
- src/service/v2_game_role.go
- src/wire/service.go
- src/wire/wire_gen.go
した。テストは追加していない。
wire対応を含んでおり、ローカルでの動作確認をしてある。
> ゲームの管理権限関連のAPIのhandler実装

- docs/openapi/v2.yaml
- src/handler/v2/game_role.go
- src/service/v2/game_role.go
- src/service/v2_errors.go
- src/service/v2_game_role.go
- src/wire/service.go
- src/wire/wire_gen.go
> ゲーム管理権限関連のAPI実装

- src/handler/v2/game.go
- src/handler/v2/game_test.go
クエリパラメータの`all`がデフォルトでtrueであるべきが、falseになっていたので修正した。
> GET /games の修正

- src/repository/v2_admin_auth.go
- src/service/v2/admin_auth.go
- src/service/v2_admin_auth.go
- src/service/v2_errors.go
> admin関連APIのservice実装

- src/repository/gorm2/migrate/current.go
- src/repository/gorm2/migrate/migrate.go
- src/repository/gorm2/migrate/v7.go
- src/repository/gorm2/v2_admin_auth.go
> admin関連のAPIのrepository実装

- src/repository/gorm2/migrate/migrate.go
- src/repository/gorm2/migrate/v6.go
- src/repository/gorm2/migrate/v8.go
v1からv2へのデータのマイグレーションを追加した。
staging、productionのデータをエクスポートして、手元で再現した環境で動作することを確認した。
> v2 api用のマイグレーション追加

- docs/openapi/v2.yaml
- src/handler/v2/checker.go
EditionGameAuthがいらなくなったので削除した。
> EditionGameAuth除去

- src/cache/ristretto/metrics.go
- src/cache/ristretto/seat.go
- src/cache/ristretto/user.go
- src/cache/seat.go
- src/config/cache.go
- src/config/v1/cache.go
- src/service/v2/seat.go
- src/wire/cache.go
- src/wire/wire_gen.go
> 席管理にキャッシュ設定

- src/handler/v2/checker.go
> checkerからログ削除

- src/repository/gorm2/v2_game_test.go
> TestGetGamesByIDs追加

- src/repository/gorm2/v2_game_test.go
順不同のものが順番も同じでないと通らなくなっていたので、修正した。
> TestGetGamesByIDsV2がflakyになっていた問題修正

- src/service/v2/edition_test.go
`service/v2/edition.go`のUpdateEditionへのテストを追加した
> TestUpdateEditionを追加

- src/repository/gorm2/edition_test.go
した。
`TestSaveEdition`,`TestUpdateEdition`,`TestDeleteEdition`の3つは追加されており、他のは追加されていない。
> repositoryのedition関連APIテスト一部追加

- src/service/v2/admin_auth.go
> adminでのぬるぽ修正

- src/handler/v2/admin.go
- src/handler/v2/admin_test.go
- src/wire/wire_gen.go
> 管理者apiのhandler実装

- go.mod
> :arrow_up: go modのバージョンを1.21.2に

- README.md
- Taskfile.yml
- docker/dev/compose.yaml
> 開発環境にAdminerを導入

- src/handler/v2/game.go
- src/handler/v2/game_genre.go
> ゲームのジャンル変更のhandler関数をgame_genre.goへ

- src/service/v2/game_test.go
mockの使い方がよくなかった。
テストケースのフィールドを増やしてmockの設定を丁寧にした
> :bug: service.CreateGameでテストが正しく実行されていなかったのを修正

- .github/workflows/ci.yaml
`file` -> `files`
___
configuration changes
___
- Codecov アクションの設定で、`file` を `files` に修正しました。
- これにより、カバレッジデータのアップロードが正しく行われるようになります。
___
<tr>
<td>
<details>
<summary><strong>ci.yaml</strong><dd><code>Codecov アクション設定の修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ci.yaml
- 修正: `file` を `files` に変更
- Codecov アクションの設定を更新
</details>
</td>
<td><a …
> :wrench: codecovの設定修正

- docker/dev/Dockerfile
- src/handler/v2/api.go
Enhancement
___
- コード生成を go tool に変更
- Dev用DockerのENTRYPOINTをgo tool化
___
```mermaid
flowchart LR
gen["go:generate コマンド"] -- "go run -> go tool" --> oapi["oapi-codegen 実行方法変更"]
docker["Docker dev ENTRYPOINT"] -- "go run -> go tool" --> air["Air 実行方法変更"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api.go</strong><dd><code>oapi-codegenをgo toolで実行</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> go run から go toolに変更

- src/repository/gorm2/v2_game_play_log.go
- src/repository/gorm2/v2_game_play_log_test.go
- src/wire/repository.go
Tests, Enhancement
___
- V2プレイログリポジトリの骨組み追加
- GetGamePlayLog 実装とテスト
- 未実装メソッドのテスト雛形追加
- DIにGamePlayLogV2を登録
___
```mermaid
flowchart LR
Repo["GamePlayLogV2 実装"] -- "GetGamePlayLog 実装" --> Get["GetGamePlayLog"]
Repo -- "Create/Update/Stats 追記" --> TODO["未実装(TODO)"]
Test["リポジトリテスト追加"] -- "正常/異常系" --> GetT["TestGetGamePlayLog"]
Test -- "雛形" --> CreateT["TestCreateGamePlayLog"]
Test -- "雛形" --> UpdateT["TestUpdateGamePlayLogEndTime"]
Test -- "雛形" --> StatsT["TestGet(Game/Edition)PlayStats"]
Wire["wire登録"] -- "DIバインド" --> Bind["repository.GamePlayLogV2"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …
> Issue1344 ebisen
