traPtitech/trap-collection-server

docs/dist/index.html

swaggerがブラウザで見れなくなっていた（すみません…）ので修正しました。

swaggerを見えるようにする

---

docs/swagger/openapi.yml

選択型の回答で回答がラベルだけで投げ込まれるとサーバー側で闇が生まれることが分かったので、質問・回答関連のエンドポイント全般に変更を入れました。
管理者用クライアント・ランチャーともに影響があるので、チェックお願いします。

question関連のエンドポイントの仕様の変更

---

docs/swagger/openapi.yml
generate/router.mustache

`/api`がエンドポイントに入るように直した。
結局、原因はopenapi.yamlのbasepathの定義の仕方だった。
ついでに、一箇所だけ無意味に3重中括弧なのも気持ち悪いので直した。
Close #39

basepathがコードに入るように

---

docker/dev/Dockerfile
docker/mock/server.Dockerfile
docker/staging/Dockerfile
model/db.go
model/db_mock.go

不要な構造体が含まれてしまい、test時にしか必要ない`go generate`で生成されるコードに依存するファイルがないとbuildが通らなくなっていた。
tagを使ってこの構造体をbuild時に除外できるようにした。
これによってmockも動くようになるはず。

build時に不要な部分を除外

---

README.md
mockgen.sh

`.env`の話が抜け落ちていたので加えた。
また、以前と違って今はdocker-composeのみで起動できるようになっており、わざわざシェルスクリプトを使う必要性もなくなったので、`mockgen.sh`を削除してREADMEの立ち上げ方法も変えた。

mock立ち上げ方法の記述の修正

---

docs/swagger/openapi.yml

集会で指摘された
- GET /games/maintainersがいらない
- /games/maintainer/{{gameID}}という名前が不自然
の修正

集会を踏まえてのOpenAPI修正

---

.dockerignore
.realize.yaml
docker/dev/Dockerfile
docker/dev/docker-compose.yml

devの起動時にローカルにopenapiディレクトリがあると、volumeのマウント時にopenapiディレクトリが上書きされていたもんだいをなおした。
これでopenapiの変更時に毎回コード生成をしないでも良くなるはず。

openapiが上書きされる問題修正

---

docs/schema.md
docs/swagger/openapi.yml
router/seat.go

席管理・ランチャーの権限管理修正をDB Schema、OpenAPIに反映させた。
既存の席管理関係のコードでコード生成と干渉してしまうものはコメントアウトしている。
認証は
1. 管理者用UIからプロダクトキー発行(同時に複数個発行可能)
2. 販売時にプロダクトキーを渡す
3. ランチャーでプロダクトキーを用いてログインし、期限付きのアクセストークン取得
4. ランチャーはアクセストークンを用いてエンドポイントを叩く
の流れ。
席管理は
1. 管理者用UIからランチャーバージョンに紐付いた席バージョン作成
2. 各ランチャーに席バージョンと席番号を設定
3. ランチャーは着席・離席エンドポイントをそれを用いて叩く
の流れ。席バージョンの作成がないと販売するランチャーで着席・離席エンドポイントが叩かれる可能性があるためこのような流れになっている。

席管理・ランチャーの権限管理修正(docs)

---

docs/swagger/openapi.yml

ランチャーの認証方式はBearerの方が表記として適切なので修正。

bearer tokenに修正

---

docs/swagger/openapi.yml
model/game_versions.go
router/game.go

windows,macを取れるようにしていたが、Nodejsの`process.platform`に合わせてwin32,darwinにした。

クエリパラメーターoperatingSystemを修正

---

model/db.go

charsetの指定がない結果、旧migrateでmigrateされるテーブルと新migrateでmigrateされるテーブルでcharsetが違くなって外部キー制約を張れなくなっていた。

旧migrateでcharset指定

---

docker/dev/docker-compose.yml
go.mod
go.sum
main.go
session/session.go

リクエストが来ていないときにRevokeする必要などもなく、cookie利用の方がhandlerでDBを触るような面倒なことを回避できるため、cookieへ暗号化して保存する方式に変更した。
また、secretを環境変数から読み込んだものに変更している。

sessionの保存場所をcookieに

---

main.go
pkg/common/types.go
src/handler/v1/api.go
src/handler/v1/session.go
src/wire.go
src/wire_gen.go

セッションの基盤を作った。
旧実装とうまく繋がるようにしているため、新アーキテクチャで設定されたセッションは旧実装でも使えるようになっている。

新アーキテクチャ用のセッション基盤作成

---

go.mod
go.sum
src/auth/user.go
src/cache/errors.go
src/cache/user.go
src/domain/values/trap_member.go
src/service/user.go
src/service/v1/user.go
src/service/v1/user_test.go

userサービスを実装した。
旧実装では毎回traQにリクエストを飛ばしていたが、新実装ではin-memory cacheを入れてリクエストを飛ばす回数を削る。

userサービス実装

---

.gitignore
src/repository/game_image.go
src/service/errors.go
src/service/game_image.go
src/service/v1/game_image.go
src/service/v1/game_image_test.go
src/storage/errors.go
src/storage/game_image.go
src/storage/mock/game_image.go

実装した。
storageはファイルの保存場所。
本番環境ではConoHaのオブジェクトストレージにローカルファイルでのキャッシュを挟んだものを使用する。
手元での動作確認用にローカルファイルのみのものも実装する予定。
io.Reader・Writer周りのモックが自動生成のものだとうまくいかないので、自動生成のものを修正している。

GameImageサービス実装

---

src/service/v1/game_image.go
src/service/v1/game_image_test.go

TeeReaderを使っていたが、`ReadAll`しておらずある程度大きい画像だとうまく動いていなかった。
テストでは100px x 100pxの画像を生成して使っていたため引っ掛かっていなかった。
今回のような場合でも引っかかるようにテストで使う画像を3000px x 3000pxのかなり大きめの画像に変更している(修正前の状態でテストに落ちた画像の大きさがこれだった)。

GameImageサービスのバグ修正

---

go.mod
go.sum
pkg/common/types.go
src/storage/swift/client.go
src/storage/swift/client_test.go
src/storage/swift/game_image.go
src/storage/swift/game_image_test.go

オブジェクトストレージへの保存部分を実装した。
オブジェクトストレージとの通信に使うパッケージは、テストのためのmockサーバー機能などがより充実していたためgophercloudのものから https://github.com/ncw/swift に変更している。
https://github.com/djherbis/fscache を用いてのアプリケーション側でのキャッシュも実装している。

GameImageのオブジェクトストレージとの接続部分実装

---

src/service/v1/launcher_auth.go

トランザクションを消したときにエラーハンドリングを消すのを忘れており、2重でエラーハンドリングをしている箇所があったので修正した。

二重のエラーハンドリング修正

---

src/domain/game_file.go
src/domain/values/launcher_environment.go
src/domain/values/launcher_environment_test.go
src/repository/game_file.go
src/repository/game_version.go
src/repository/gorm2/game_version.go
src/repository/gorm2/game_version_test.go
src/service/errors.go
src/service/game_file.go
src/service/v1/game_file.go
src/service/v1/game_file_test.go
src/storage/game_file.go
src/storage/mock/game_file.go

#205 でのGameFileサービス実装した際にGameVersionインターフェイスに変更が発生し、コンパイルが通らなくなったのでmainへの取り込みを保留していた。
#206 でgorm2実装の修正が完了したので取り込む。

GameFileサービス実装とGameVersionリポジトリ修正取り込み

---

src/domain/game_image.go
src/repository/gorm2/game_image.go
src/repository/gorm2/game_image_test.go
src/service/v1/game_image.go
src/service/v1/game_image_test.go
src/storage/local/game_image_test.go
src/storage/swift/game_image_test.go

ImageドメインにcreatedAtを入れていなかったが、ランチャー起動時に取得するゲームの画像などの更新情報取得時に必要で、アプリケーション内で扱う情報だったので追加した。

ImageドメインにcreatedAt追加

---

docker/dev/docker-compose.yml
main.go
pkg/common/types.go
src/wire.go
src/wire_gen.go

今までCOLLECTION_ENVによってオブジェクトストレージを使うか分岐していたが、STORAGEによって分岐するようにした。
これによってstagingでもdebugのログを吐けるようになる。

環境変数STORAGE追加

---

src/service/v1/launcher_auth.go

access tokenの有効期限を1hから24hに変更した。
これ以降新たに発行されるaccess tokenの有効期限は24時間になる。

expiresInを1h->24hに

---

docker/staging/Dockerfile
main.go

ストレージのlocalからオブジェクトストレージへの切り替えが #231 以降機能しておらず、staging環境でobject strageにデータが保存されていなかった。
また、workdirが設定されていなかったために/にcacheディレクトリが作られ、cacheの引き継ぎができていなかった。

ストレージ切り替えのバグ修正

---

.github/workflows/main.yaml

codecov.txtのパスが #248 以降誤っており、codecovが正常に動いていなかった。

codecovのpath修正

---

src/repository/gorm2/metrics.go
src/storage/swift/client_test.go
src/storage/swift/game_file_test.go
src/storage/swift/game_image_test.go
src/storage/swift/game_video_test.go

アクセストークンのメトリクス、別に間違っていなかった

---

generate/controller-api.mustache
generate/generator.groovy
generate/interfaces.mustache
src/handler/v1/game_file.go
src/handler/v1/game_file_test.go
src/handler/v1/game_image.go
src/handler/v1/game_image_test.go
src/handler/v1/game_video.go
src/handler/v1/game_video_test.go
src/service/game_file.go
src/service/game_image.go
src/service/game_video.go
src/service/v1/game_file.go
src/service/v1/game_image.go
src/service/v1/game_video.go

PipeReaderがCloseされていないため、writeを行うgoroutineが永遠に終わらなくなっていた。
また、これによりファイルダウンロードのセマフォがロックされ続け、ファイルのダウンロードができなくなっていた。
#287 と合わさって、m011のCPU 100%張り付きの原因となっていた可能性が高い。

PipeReaderのClose忘れ

---

.github/dependabot.yaml

依存関係のupdateを土曜日にまとめてやった方が都合が良いなぁ、と最近思ったので、金曜日中にdependabot回して起きたら確認してmergeすれば良い感じにした。

dependabotを金曜日に動くように

---

src/config/v1/app.go

アプリケーション環境からmock削除

---

.github/workflows/ci.yaml

setup-goに追加された、go.modでGoのversionを設定する機能を利用してGitHub ActionsのGoのバージョン指定をするようにした。
ref: https://github.com/actions/setup-go/releases/tag/v3.1.0

go.modでciのgoのバージョン設定

---

.github/workflows/ci.yaml
.gitignore
docker/base/compose.yaml
docker/dev/Dockerfile
docker/dev/compose.yaml
docker/test/Dockerfile
docker/test/compose.yaml

やりたくなったのでサクッとやってしまった。
主に
- extendでのdb絡みの部分の共通化
- healthcheckによるdockerizeの置き換え
- airのバージョン更新
- GitHub Actionsの`go generate`を必要になる各jobで行うように変更
- job起動時間とdownload artifactの時間、jobのフローみた感じ、共通化するメリットなさそうなため
Close #380

docker関連のrefactoring

---

.github/workflows/ci.yaml

自前で色々キャッシュしないで良くなったので、自前のキャッシュ実装を消して書き換えた。

setup-goのcache対応

---

docker/dev/Dockerfile
docker/production/Dockerfile
docker/test/Dockerfile

以下を行った。
- docker/dockerfileのバージョンを1に統一
- `mount=type=cache`を使うべきだが使っていなかった箇所に追加
imageサイズ、Timezoneなどの挙動ともに変化がないことを手元で確認ずみ。
Close #392

Dockerfileの細かい調整

---

docker/production/Dockerfile

GitHub Actionsでのbuildに失敗したので戻す。
複数アーキテクチャのキャッシュが混在したりが怪しい気がしている。

productionのDockerfileからキャッシュ削除

---

src/storage/local/game_file.go
src/storage/local/game_file_test.go
src/storage/local/game_image.go
src/storage/local/game_image_test.go
src/storage/local/game_video.go
src/storage/local/game_video_test.go
src/storage/swift/client.go
src/storage/swift/client_test.go
src/storage/swift/game_file.go
src/storage/swift/game_file_test.go
src/storage/swift/game_image.go
src/storage/swift/game_image_test.go
src/storage/swift/game_video.go
src/storage/swift/game_video_test.go

storageのGetGameFile,GetGameImage,GetGameVideoが全てredirectに置き換えられておりいらないので削除した。
これに伴い、swift packageのloadFileがTestでしか使わなくなったので、`client_test.go`へ移動した。
また、Unit Testが存在しなかったGetTempURLのUnit TestがほぼGetGameFile,GetGameImage,GetGameVideoのテストの流用で実現できたので、書き換えて流用した。

storageのGetGameFile,GetGameImage,GetGameVideo削除

---

src/handler/v2/api.go

oapi-codegenにvalidatorがrootパスに設定しないと正常に動作しない問題があったため、その対応。

validatorの設定方法修正

---

src/handler/v2/api.go
src/handler/v2/game_image.go
src/handler/v2/game_image_test.go
src/service/v2/game_image.go
src/service/v2/game_image_test.go
src/service/v2_game_image.go
src/wire/repository.go
src/wire/service.go
src/wire/wire_gen.go

実装した。
oapi-codegenで画像データ周りのバリデーション時にデータが全てメモリにのることがわかったので、`ExcludeRequestBody`、`ExcludeResponseBody`を有効にしてバリデーションを切っている。

ゲーム画像関連のhandler実装

---

src/repository/errors.go
src/repository/gorm2/v2_game.go
src/repository/gorm2/v2_game_test.go
src/repository/v2_game.go
src/service/v2/game.go
src/service/v2/game_test.go
src/service/v2_errors.go

全てのゲームを取得して、配列の長さから全ゲームの個数を、limit,offsetをかけて必要なゲームを取得していた。
SQL文にLimitとOffsetをつけて必要なだけゲームを取得し、全ゲームの個数はCountを使って別途取得するようにした。

Game関連のAPIでSQL文を適切に修正

---

docs/openapi/v2.yaml

staging環境でoapi-codegenのmiddlewareがpathのmatchに失敗する影響でv2 APIがうまく動作していなかった。
proxyありの環境下でしか再現しないため、これで治るかのチェックはできていない。

staging環境のoapi-codegenのmatch修正

---

src/handler/v2/game_version.go
src/handler/v2/game_version_test.go

`GET /games/:gameID/versions`でlimitもoffsetもない時`400 invalid limit`になっていたので、修正した。

ゲームバージョンの実装ミス修正

---

src/handler/v2/checker.go
src/repository/edition.go
src/repository/gorm2/access_token.go
src/repository/gorm2/edition.go
src/service/edition_auth.go
src/service/v2/edition_auth.go

実装した。
テストなし。
`GET /games/{gameID}`に関しては、ランチャーから上手く叩けなくなっているのをどうにかする必要がある。

エディションの認可周りのchecker実装

---

src/handler/v2/checker.go
src/handler/v2/checker_test.go
src/wire/wire_gen.go

した。テストは存在しない。
`AdministratorAuth`はv1のものを使っている。
ローカルでの動作は、
- owner、maintainerではないゲームをいじれない
- ownerであるとき、いじれるし消せる
- maintainerのときいじれるけど消せない
ことを確認した。

ゲームの権限チェック周りの実装

---

src/handler/v2/game_file.go

fileTypeが`win32`ではなく`windows`になっていた。
oapi-codegenの生成コードの変数で統一してしまいたかったので、switchを修正しておいた。

win32のファイルがPOSTできない問題修正

---

docs/openapi/v2.yaml

権限の設定ミスで、traPのメンバーの誰でもpostできるようになっていたので、修正した。

画像、動画、ファイルを管理者以外もpostできていた問題修正

---

docs/openapi/v2.yaml

OpenAPI Generatorのバグでクライアントの生成がうまくいかないので、暫定的にNewGameFileのtypeフィールドをstringにした。

NewGameFileのtypeをstringに

---

src/config/app.go
src/config/v1/app.go
src/config/v1/env.go
src/handler/v1/game.go
src/handler/v1/game_file.go
src/handler/v1/game_file_test.go
src/handler/v1/game_image.go
src/handler/v1/game_image_test.go
src/handler/v1/game_role.go
src/handler/v1/game_role_test.go
src/handler/v1/game_test.go
src/handler/v1/game_url.go
src/handler/v1/game_url_test.go
src/handler/v1/game_version.go
src/handler/v1/game_version_test.go
src/handler/v1/game_video.go
src/handler/v1/game_video_test.go
src/handler/v1/launcher_auth.go
src/handler/v1/launcher_auth_test.go
src/handler/v1/launcher_version.go
src/handler/v1/launcher_version_test.go
src/wire/wire_gen.go

v1の書き込み系apiを停止する環境変数`FEATURE_V1_WRITE`を作った。
この環境変数にfalseを設定すると、
認証系を除いてpost、delete、patchのapiを使えなくなる。
v1からv2への移行用に設定。
デフォルトはtrueなので、デフォルトの動作に変更はない。

v1の書き込み系api停止用環境変数作成

---

src/repository/gorm2/edition.go
src/service/v2/edition.go

エディションに登録された後にゲームが削除されたときにエディションのゲーム一覧のGET自体が500になっていたので修正した。
本番環境のデータでチェック済み。

エディションのゲームが削除されていた場合の対応

---

src/handler/v2/game_file.go
src/handler/v2/game_file_test.go
src/repository/gorm2/v2_game_file.go
src/repository/gorm2/v2_game_file_test.go

#486 で追加されていなかったrepositoryの`GetGameFilesWithoutType`以外とhandlerのテストを追加した。
また、その過程で見つけたハッシュ関係のバグを修正した。具体的には、
- handlerでhashをstringにエンコードしていなかった
- repositoryの`GetGameFile`,`GetGameFiles`でstringをhashにデコードしていなかった
のを適切に修正した。
クライアントではハッシュを現状使ってないらしいのであまり影響はなさそう。

gameファイル関連のAPIのテスト追加

---

src/repository/gorm2/db.go
src/repository/gorm2/v2_metrics.go

これまで、DB周りのメトリクスはv1のテーブルを参照していたので、v2 APIが有効化されているときにはv2のテーブルを参照するようにした。

v2のメトリクス追加

---

src/repository/gorm2/migrate/v8.go
src/service/v2/edition.go

`created_at`での`ORDER BY`が全て`DESC`が抜けており、
最新ではなく最も古い画像、動画がゲームバージョンに紐づき、
最も古いゲームバージョンがエディションに紐づいていた。

v8のmigration修正

---

src/repository/edition.go
src/service/v2/edition_test.go

service層のEditionに対して、以下のメソッドにテストを追加
- CreateEdition
- GetEditions
- GetEdition
その他のメソッドのテストは別PRで追加する

serviceのCreateEdition、GetEditions、GetEditionのテストを追加

---

src/repository/gorm2/edition.go

Selectで明示的に更新対象のフィールドの指定を行うようにした
https://gorm.io/docs/update.html#Update-Selected-Fields
sql.NullStringでValidがfalseのもの(ゼロ値の状態)は、普通の書き方だとUpdateの対象とならないため
>NOTE When updating with struct, GORM will only update non-zero fields. You might want to use map to update attributes or use Select to specify fields to update
https://gorm.io/docs/update.html#Updates-multiple-columns

repositoryのUpdateEditionでのgormのupdateメソッドの書き方を変更

---

src/service/v2/seat.go

席数を増やして席を追加した際に`append`でnillが追加され、ぬるぽしていた。

席数変更でぬるぽしていた

---

.github/workflows/deploy-ci.yaml

armのimageのbuildに時間がかかるので、mainへのmerge時のarmのbuildをしないようにした。

staging用デプロイ時のarm image削除

---

src/handler/v2/checker.go

errorをwrapしたことで`*echo.HTTPError`型でなくなってしまい、
https://github.com/deepmap/oapi-codegen/blob/ab90f1927bc5ec3e29af216d4298fbb4780ae36d/pkg/middleware/oapi_validate.go#L169
に引っかからなくなっていた。
echo的にも`*echo.HTTPError`をwrapするのはあまり良くなさそうなので、修正した。

checkerのエラーのstatusコードが全て403になっていた

---

src/handler/v2/users.go
src/handler/v2/users_test.go

370行目~373行目の
ここの直し方が分かりません。
ver1ではusersは
このように定義されているので、[]*openapi.User型が入っているのですが、v2ではerr型であるため、比べるものが変わってしまっています。
他のファイルを参考にしようとすると、v2/game_image_testの最後らへんが近そうなことをしているのですが、
上のように書いてあったので、参考にしながら書いてみたのですが全然違うと思います。
どうすれば370-373行目を実装できるでしょうか？よろしくお願いします。

users_test の実装

---

README.md
docker/dev/Caddyfile
docker/dev/compose.yaml
docker/dev/proxy.Dockerfile

追加した。
`http://localhost:8080`を開くことでWebUIにアクセスできる。
Caddyでプロキシして、Web UIの静的配信とサーバーに振り分けている。
現時点では、初期adminの追加がないためdb直いじりで初期adminの追加をしないadminになれない。
Close #525

ローカルの開発環境にwebui追加

---

.github/workflows/deploy-ci.yaml

stagingのdeploy.shをproductionと共通化したため必要になったstagingへのデプロイのGitHub Actionsの修正。

stagingのdeploy.shのproductionとの共通化対応

---

src/handler/api.go

ログが10秒ごとに叩かれるmetricsのエンドポイントで埋め尽くされてしまっているので、metrics用エンドポイントのみログをはかないよう設定を変更した。

metricsのエンドポイントをログから除外

---

.github/workflows/ci.yaml

#559 によりoapi-codegenの生成ファイルを含めたため、GitHub Actionsからoapi-codegenのコード生成を除外した。

GitHub Actionsからoapi-codegenのコード生成削除

---

.github/workflows/ci.yaml

codecovのGitHub Actionがv4になったときにtokenが必要になった
https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes

:wrench: CodeCovのsecretを使う

---

docker/base/compose.yaml

extendsを使ったときにdepends_onを使えなくなっていたので、削除した。
___
configuration changes
___
- `docker/base/compose.yaml`ファイルから`depends_on`セクションを削除し、`mariadb`サービスの依存関係を解消しました。
- `extends`を使用する際に`depends_on`が使えない問題に対処しました。
___
<tr>
<td>
<details>
<summary><strong>compose.yaml</strong><dd><code>`depends_on`セクションの削除による依存関係の解消</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docker/base/compose.yaml
- `depends_on`セクションを削除
- `mariadb`サービスの依存関係を削除
</details>
</td>
<td><a …

docker composeのdepends_onを削除

---

.github/workflows/ai-review.yaml

configuration changes
___
- `.github/workflows/ai-review.yaml`において、`IGNORE.GLOB`に`['*.gen.go']`を追加し、自動生成されるGoコードを無視するように設定を変更。
___
<tr>
<td>
<details>
<summary><strong>ai-review.yaml</strong><dd><code>自動生成コードを無視する設定の追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ai-review.yaml
- `IGNORE.GLOB`に`['*.gen.go']`を追加
</details>
</td>
<td><a …

:wrench: ai reviewで自動生成されるコードを無視するように設定

---

src/handler/v2/game.go
src/handler/v2/game_test.go
src/repository/gorm2/v2_game.go
src/repository/gorm2/v2_game_test.go
src/repository/gorm2/visibility.go
src/service/v2/game.go
src/service/v2/game_test.go
src/service/v2_game.go

fix: #778 
- **:sparkles: serviceでvisibilityを更新できるようにした**
- **:sparkles: repositoryでvisibilityを変更する実装を追加**
- **:white_check_mark: getVisibilityのテスト**
- **:sparkles: handlerでvisibilityを更新できるようにした**
___
enhancement, tests
___
- ゲームの可視性を更新する機能を追加しました。これにより、ゲームの可視性を`PATCH /games/{gameID}`エンドポイントで変更できるようになりました。
- `visibility`フィールドのバリデーションを追加し、無効な可視性が指定された場合はエラーメッセージを返すようにしました。
- テストケースを追加し、可視性の変更が正しく行われることを確認しました。
- データベースで可視性タイプを管理するためのロジックを追加しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>game.go</strong><dd><code>ゲームの可視性を更新する機能を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

`PATCH /games/{gameID}`でvisibilityを変更できるようにする

---

.github/workflows/ci.yaml

configuration changes
___
- `.github/workflows/ci.yaml`内で、非推奨となった`fail_on_error`を`fail_level`に変更しました。
- `reviewdog/action-golangci-lint`の設定を最新の推奨形式に更新しました。
___
<tr>
<td>
<details>
<summary><strong>ci.yaml</strong><dd><code>非推奨の`fail_on_error`を`fail_level`に置き換え</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ci.yaml
<li><code>fail_on_error</code>が非推奨となったため、<code>fail_level</code>に変更。<br> <li> <code>reviewdog/action-golangci-lint</code>の設定を更新。
</details>
</td>
<td><a …

:wrench: deprecatedだったfail_on_errorをfail_levelに変更

---

Taskfile.yml
task/Taskfile_darwin.yml
task/Taskfile_linux.yml
task/Taskfile_unix.yml
task/Taskfile_windows.yml

Enhancement
___
- `Taskfile.yml`に新しいタスク`update-frontend`を追加しました。このタスクは`os:update-frontend`を呼び出します。
- 各OS（Darwin, Linux, Windows）に対応する`update-frontend`タスクをそれぞれのTaskfileに追加しました。
- Unix系システム用のTaskfileでは、Docker Composeを使用して`collection-proxy`サービスをキャッシュなしで再ビルドするコマンドを追加しました。
- Windows用のTaskfileにも同様の`collection-proxy`サービス再ビルドコマンドを追加しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Taskfile.yml</strong><dd><code>Add `update-frontend` task to Taskfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Taskfile.yml
<li>Added a new task …

:wrench: Taskfileにfrontendを更新するためのコマンド追加

---

.github/workflows/ci.yaml

Enhancement, Configuration changes
___
- CIでreviewdog reporterを動的切替
- PR時はgithub-pr-reviewを使用
- 非PR時はgithub-checkを使用
___
```mermaid
flowchart LR
A["GitHub Event"] --> B{"event_name == pull_request"}
B -- "Yes" --> C["reporter = github-pr-review"]
B -- "No" --> D["reporter = github-check"]
C --> E["reviewdog/action-golangci-lint"]
D --> E
```
<details> <summary><h3> File Walkthrough</h3></summary>
<tr>
<td>
<details>
<summary><strong>ci.yaml</strong><dd><code>reviewdog reporterの動的条件切替を導入</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

:wrench: reviewdogのreporterをPRかそれ以外かで切り替え

---

.github/CODEOWNERS

Enhancement
___
- CODEOWNERS を新規追加
- 全ファイルの所有者を設定
___
```mermaid
flowchart LR
repo["リポジトリ"] -- "CODEOWNERS 追加" --> codeowners[".github/CODEOWNERS"]
codeowners -- "全ファイル(*)" --> team["@traPtitech/trap-collection-server-owners"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<tr>
<td>
<details>
<summary><strong>CODEOWNERS</strong><dd><code>ルート全体に CODEOWNERS を適用</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

:wrench: CODEOWNERSを設定する
